[package]
name="advent-of-code-2022"
version="0.1.0"
include = ["src/*.rs"]
description = "My solutions for the 2022 Advent of Code. https://adventofcode.com/2022"
license = "MIT"
documentation = "README.md"

[[bin]]
name = "day01"
path = "src/day01/main.rs"
test = false
bench = false

[[bin]]
name = "day02"
path = "src/day02/main.rs"
test = false
bench = false
